In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/consumer_preferences.csv')

In [ ]:
df

    Consumer_ID Preferred_Cuisine
0         U1001          American
1         U1002           Mexican
2         U1003           Mexican
3         U1004            Bakery
4         U1004         Breakfast
..          ...               ...
325       U1135          Southern
326       U1135         Ice Cream
327       U1136           Mexican
328       U1137           Mexican
329       U1138          Pizzeria

[330 rows x 2 columns]

In [ ]:
df.isnull().sum()

Consumer_ID          0
Preferred_Cuisine    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(2)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('consumer_preferences_cleaned.csv',index=False)

In [ ]:
df=pd.read_csv('/content/consumers.csv')

In [ ]:
df

,Consumer_ID,City,State,Country,Latitude,Longitude,Smoker,Drink_Level,Transportation_Method,Marital_Status,Children,Age,Occupation,Budget
0,U1001,San Luis Potosi,San Luis Potosi,Mexico,22.139997,-100.978803,No,Abstemious,On Foot,Single,Independent,23,Student,Medium
1,U1002,San Luis Potosi,San Luis Potosi,Mexico,22.150087,-100.983325,No,Abstemious,Public,Single,Independent,22,Student,Low
2,U1003,San Luis Potosi,San Luis Potosi,Mexico,22.119847,-100.946527,No,Social Drinker,Public,Single,Independent,23,Student,Low
3,U1004,Cuernavaca,Morelos,Mexico,18.867000,-99.183000,No,Abstemious,Public,Single,Independent,72,Employed,Medium
4,U1005,San Luis Potosi,San Luis Potosi,Mexico,22.183477,-100.959891,No,Abstemious,Public,Single,Independent,20,Student,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,U1134,San Luis Potosi,San Luis Potosi,Mexico,22.149654,-100.998610,No,Casual Drinker,Public,Single,Independent,21,Student,Medium
134,U1135,San Luis Potosi,San Luis Potosi,Mexico,22.170396,-100.949936,No,Casual Drinker,On Foot,Single,Kids,24,Student,Low
135,U1136,San Luis Potosi,San Luis Potosi,Mexico,22.149607,-100.997235,Yes,Social Drinker,Car,Single,Independent,22,Student,Low
136,U1137,San Luis Potosi,San Luis Potosi,Mexico,22.144803,-100.944623,No,Social Drinker,Public,Single,Independent,23,Student,Low
137,U1138,San Luis Potosi,San Luis Potosi,Mexico,22.152884,-100.939663,No,Social Drinker,Public,Single,Independent,21,Student,Medium

In [ ]:
df.isnull().sum()

Consumer_ID               0
City                      0
State                     0
Country                   0
Latitude                  0
Longitude                 0
Smoker                    3
Drink_Level               0
Transportation_Method     7
Marital_Status            4
Children                 11
Age                       0
Occupation                7
Budget                    7
dtype: int64

In [ ]:
df['Smoker'].fillna('No',inplace=True)
df['Transportation_Method'].fillna('Walking',inplace=True)
df['Marital_Status'].fillna('Married',inplace=True)
df['Children'].fillna(0,inplace=True)
df['Occupation'].fillna('Student',inplace=True)
df['Budget'].fillna('Medium',inplace=True)

/tmp/ipykernel_2547/1381353982.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Smoker'].fillna('No',inplace=True)
/tmp/ipykernel_2547/1381353982.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Transportation_Method'].fillna('Walking',inplace=True)
/tmp/ipykernel_2547/1381353982.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marital_Status'].fillna('Married',inplace=True)
/tmp/ipykernel_2547/1381353982.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Children'].fillna(0,inplace=True)
/tmp/ipykernel_2547/1381353982.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Occupation'].fillna('Student',inplace=True)
/tmp/ipykernel_2547/1381353982.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Budget'].fillna('Medium',inplace=True)

In [ ]:
df.isnull().sum()

Consumer_ID              0
City                     0
State                    0
Country                  0
Latitude                 0
Longitude                0
Smoker                   0
Drink_Level              0
Transportation_Method    0
Marital_Status           0
Children                 0
Age                      0
Occupation               0
Budget                   0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('consumers_cleaned.csv',index=False)

In [ ]:
df=pd.read_csv('/content/data_dictionary.csv')
df

,Table,Field,Description
0,Consumers,Consumer_ID,Unique identifier for each consumer
1,NaN,City,City where the consumer lives
2,NaN,State,State where the consumer lives
3,NaN,Country,Country where the consumer lives
4,NaN,Latitude,Latitude where the consumer lives
5,NaN,Longitude,Longitude where the consumer lives
6,NaN,Smoker,Whether the consumer smokes or not
7,NaN,Drink_Level,"Whether the consumer is an abstemious, causal,..."
8,NaN,Transportation_Method,"Whether the consumer transports on foot, by pu..."
9,NaN,Marital_Status,The consumer's marital status (single or married)
10,NaN,Children,Whether the consumer has dependent/independent...
11,NaN,Age,The consumer's age
12,NaN,Occupation,"The consumer's occupation (student, employed, ..."
13,NaN,Budget,"The consumer's budget (low, medium, high)"
14,Consumer_Preferences,Preferred_Cuisine,Types of food the consumer prefers
15,Ratings,Overall_Rating,The overall rating by the consumer for the res...
16,NaN,Food_Rating,The food's rating by the consumer for the rest...
17,NaN,Service_Rating,The service rating by the consumer for the res...
18,Restaurants,Restaurant_ID,Unique identifier for each restaurant
19,NaN,Name,The restaurant's name
20,NaN,City,The restaurant's city
21,NaN,State,The restaurant's state
22,NaN,Country,The restaurant's country
23,NaN,Zip_Code,The restaurat's zip code
24,NaN,Latitude,The restaurant's latitude
25,NaN,Longitude,The restaurant's longitude
26,NaN,Alcohol_Service,"Whether the restaurant seves no alcohol, wine ..."
27,NaN,Smoking_Allowed,"Whether any smoking is allowed, including in t..."
28,NaN,Price,"The restaurant's price (low, medium, high)"
29,NaN,Franchise,Whether the restaurant is a franchise
30,NaN,Area,Whether the restaurant is in an open or closed...
31,NaN,Parking,Whether the restaurant offers any sort of park...
32,Restaurant_Cuisines,Cuisine,Types of food the restaurant serves

In [ ]:
df.isnull().sum()

Table          28
Field           0
Description     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=pd.read_csv('/content/ratings.csv')
df

     Consumer_ID  Restaurant_ID  Overall_Rating  Food_Rating  Service_Rating
0          U1077         135085               2            2               2
1          U1077         135038               2            2               1
2          U1077         132825               2            2               2
3          U1077         135060               1            2               2
4          U1068         135104               1            1               2
...          ...            ...             ...          ...             ...
1156       U1043         132630               1            1               1
1157       U1011         132715               1            1               0
1158       U1068         132733               1            1               0
1159       U1068         132594               1            1               1
1160       U1068         132660               0            0               0

[1161 rows x 5 columns]

In [ ]:
df.isnull().sum()

Consumer_ID       0
Restaurant_ID     0
Overall_Rating    0
Food_Rating       0
Service_Rating    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=pd.read_csv('/content/restaurant_cuisines.csv')
df

     Restaurant_ID    Cuisine
0           132560   Regional
1           132572  Cafeteria
2           132583   American
3           132584    Mexican
4           132594    Mexican
..             ...        ...
107         135086  Fast Food
108         135088  Cafeteria
109         135104    Mexican
110         135106    Mexican
111         135109    Italian

[112 rows x 2 columns]

In [ ]:
df.isnull().sum()

Restaurant_ID    0
Cuisine          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=pd.read_csv('/content/restaurants.csv')
df

,Restaurant_ID,Name,City,State,Country,Zip_Code,Latitude,Longitude,Alcohol_Service,Smoking_Allowed,Price,Franchise,Area,Parking
0,132560,Puesto de Gorditas,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752304,-99.166913,NaN,Yes,Low,No,Open,Public
1,132561,Cafe Ambar,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.726819,-99.126506,NaN,No,Low,No,Closed,NaN
2,132564,Church's,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.730925,-99.145185,NaN,No,Low,No,Closed,NaN
3,132572,Cafe Chaires,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.141647,-100.992712,NaN,No,Low,No,Closed,Yes
4,132583,McDonalds Centro,Cuernavaca,Morelos,Mexico,62000.0,18.922290,-99.234332,NaN,No,Low,Yes,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,135088,Cafeteria Cenidet,Cuernavaca,Morelos,Mexico,NaN,18.876011,-99.219890,NaN,No,Low,No,Closed,Public
126,135104,Vips,Ciudad Victoria,Tamaulipas,Mexico,NaN,23.752982,-99.168434,Full Bar,No,Medium,Yes,Closed,Yes
127,135106,El Rincón De San Francisco,San Luis Potosi,San Luis Potosi,Mexico,78000.0,22.149709,-100.976093,Wine & Beer,Bar Only,Medium,No,Open,NaN
128,135108,Potzocalli,San Luis Potosi,San Luis Potosi,Mexico,NaN,22.136253,-100.933585,NaN,No,Low,No,Closed,NaN
129,135109,Paniroles,Cuernavaca,Morelos,Mexico,NaN,18.921785,-99.235350,Wine & Beer,No,Medium,No,Closed,NaN

In [ ]:
df.isnull().sum()

Restaurant_ID       0
Name                0
City                0
State               0
Country             0
Zip_Code           74
Latitude            0
Longitude           0
Alcohol_Service    87
Smoking_Allowed     0
Price               0
Franchise           0
Area                0
Parking            65
dtype: int64

In [ ]:
df['Alcohol_Service'].fillna('No',inplace=True)
df['Zip_Code'].fillna(11372,inplace=True)
df['Parking'].fillna('Street',inplace=True)

/tmp/ipykernel_2547/2150776460.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Alcohol_Service'].fillna('No',inplace=True)
/tmp/ipykernel_2547/2150776460.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Zip_Code'].fillna(11372,inplace=True)
/tmp/ipykernel_2547/2150776460.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Parking'].fillna('Street',inplace=True)

In [ ]:
df.isnull().sum()

Restaurant_ID      0
Name               0
City               0
State              0
Country            0
Zip_Code           0
Latitude           0
Longitude          0
Alcohol_Service    0
Smoking_Allowed    0
Price              0
Franchise          0
Area               0
Parking            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv('restaurants_cleaned.csv',index=False)